// 公共部分多语言
module.exports = {
  zh: {
    home: '首页',
    telling: '算命',
    cart: '购物车',
    personal: '个人',
    birth: '生辰八字',
    wds: '问大师',
    jpclass: '精品课程',
    more: '更多',
    gobuy: '去购买',
    carts: '购物车',
    editor: '编辑',
    emptygoods: '购物车空空如也，快去选购商品吧~',
    goodshot: '逛逛店铺热卖',
    youlike: '你可能喜欢',
    defaults: '默认',
    completes: '完成',
    Totalselection:'全选',
    deletes: '删除',
    mycoupon: '我的优惠券',
    gouse: '去使用',
    goodsdetails: '商品详情',
    twdetails: '图文详情',
    parameters: '商品参数',
    attention: '购买须知',
    customerservice:'客服',
    joinbuy:'加入购物车',
    buy: '立即购买',
    cancel:'取消',
    myorder: '我的订单',
    orderdetails: '订单详情',
    loginfo: '物流信息',
    system: '系统',
    orderpay: '你的订单已生产，请立即支付',
    payment: '支付金额',
    note: '备注信息',
    ordernum: '订单编号',
    ordertime: '下单时间',
    paymethod: '支付方式',
    gopay: '如是待支付时，去支付',
    cancellation: '取消订单',
    immepayment: '立即支付',
    looklog: '查看物流',
    receipt: '确认收货',
    binding: '绑定',
    allorders: '全部订单',
    waitpay: '待付款',
    waitgoods: '待收货',
    completed: '已完成',
    serviced: '售后服务',
    myaddress: '我的地址',
    OnlineService: '在线客服',
    setup: '设置',
    messagecenter: '消息中心',
    AllMarkedRead: '全部标记为已读',
    AkeyEmpty: '一键清空',
    cancelqx: '取消',
    emptyAll: '是否清空所有消息',
    carefulEmpty: '清空后无法恢复，请谨慎处理',
    determine: '确定',
    setpersonal: '修改个人资料',
    headportrait: '头像',
    personaldata: '个人资料',
    bindingz: '绑定支付宝',
    wbinding: '未绑定',
    feedback: '意见反馈',
    shot: '拍摄',
    chooseimg: '从相册选择',
    exitlogon: '退出登录',
    phoneretrieval: '手机找回',
    retrpwd:'使用注册手机号码找回',
    next: '下一步',
    phone: '手机快捷登录',
    uselogin: '用户登录',
    phonekc: '登录k.chan，解锁更多功能',
    login: '登录',
    register: '注册',
    agree: '未注册手机号码登录即可自动注册，并代表您已同意用户协议',
    uesrpwd: '账号密码登录',
    wx: '微信登录',
    qq: 'qq登录',
    wb: '微博登录',
    username: '用户名',
    pwd: '密码',
    creat: '创建账户',
    forget: '忘记密码',
    send: '点击发送验证码',
    repwd: '重置密码',
    submit: '提交',
    reset: '重置',
    placeholder: {
       allsearch: '全局搜索',
       userphone: '请输入手机号',
       userpwd: '请输入密码',
       enteryzm: '请输入验证码',
       resetpwd: '请确认密码',
       enterxq: '请输入您的特殊需求',
       entering: '请输入...',
       username: '请输入用户名',
       search: '搜索'
    },
    nobirth: '你还未添加生辰八字',
    add: '添加',
    sm: '算命',
    bazi: '生辰八字',
    name: '姓名',
   gender: '性别',
   nan: '男',
   nv: '女',
   birthyear: '出生年月',
   birthtime: '出生时辰',
   birthaddress: '出生地',
   fellback: '意见反馈',
   liuyan:'如果您在网站和微商城发现任何问题，或者有更好的建议，欢迎给我们留言！',
   yishou: '已售',
   jian:'件',
   paystyle: '支付方式',
   wxpay: '微信支付',
   tuiwx: '推荐已在微信中绑定银行卡的用户使用',
   alipay: '支付宝支付',
   tuialipay: '安全快捷，可支持银行卡支付',
   tuivisapay: '支持国际支付',
   useyouhui: '可用优惠券',
   orderinfo: '订单信息',
   ordergoodslist: '商品清单',
   orderdily: '发货信息',
   orderinfopay: '支付信息',
   ordertal: '总计',
   orderbz: '备注',
   newaddress: '新建收货地址',
   addressshou: '新建收获地址，保证商品顺利送达',
   shipaddress: '收获地址',
   noshipaddress: '没有收获地址寄不了快递哦',
   addressadd: '添加',
   nowdefault:'当前默认',
   updefault: '设为默认',
   addressjia: '+ 新建地址',
   editoradd: '编辑/添加地址',
   deleteguoqi: '删除已过期优惠券',
   jiesuan: '结算',
   submitorder: '提交订单',
   yibuy: '已购买',
   restsend: '重新发送'
   
  },
  char: {
    home: '首頁',
    telling: '算命',
    cart: '購物車',
    personal: '個人',
    birth: '生辰八字',
    wds: '問大師',
    jpclass: '精品課程',
    more: '更多',
    gobuy: '去購買',
    carts: '購物車',
    editor: '編輯',
    emptygoods: '購物車空空如何，快去選購商品吧~',
    goodshot: '逛逛店鋪熱賣',
    youlike: '妳可能喜歡',
    defaults: '默認',
    completes: '完成',
    Totalselection: '全選',
    deletes: '刪除',
    mycoupon: '我的優惠券',
    gouse: '去使用',
    goodsdetails: '商品詳情',
    twdetails: '圖文詳情',
    parameters:'商品參數',
    attention: '購買須知',
    customerservice: '客服',
    joinbuy:'加入購物車',
    buy: '立即購買',
    cancel: '取消',
    myorder: '我的訂單',
    orderdetails: '訂單詳情',
    loginfo: '物流信息',
    system: '系統',
    orderpay: '妳的訂單已生產，請立即支付',
    payment: '支付金額',
    note: '備註信息',
    ordernum: '訂單編號',
    ordertime: '下單時間',
    paymethod: '支付方式',
    gopay: '如是待支付時，去支付',
    cancellation: '取消訂單',
    immepayment: '立即支付',
    looklog: '查看物流',
    receipt: '確認收貨',
    binding: '綁定',
    allorders: '全部訂單',
    waitpay: '待付款',
    waitgoods: '待收貨',
    completed: '已完成',
    serviced: '售後服務',
    myaddress: '我的地址',
    OnlineService: '在線客服',
    setup: '設置',
    messagecenter: '消息中心',
    AllMarkedRead: '全部標記為已讀',
    AkeyEmpty: '壹鍵清空',
    cancelqx: '取消',
    emptyAll: '是否清空所有消息',
    carefulEmpty: '清空後無法恢復，請謹慎處理',
    determine: '確定',
    setpersonal: '修改個人資料',
    headportrait: '頭像',
    personaldata: '個人資料',
    bindingz: '綁定支付寶',
    wbinding: '未綁定',
    feedback: '意見反饋',
    shot: '拍攝',
    chooseimg: '從相冊選擇',
    exitlogon: '退出登錄',
    phoneretrieval: '手機找回',
    retrpwd: '使用註冊手機號碼找回',
    next: '下壹步',
    phone: '手機快捷登錄',
    uselogin: '用戶登錄',
    phonekc: '登錄k.chan，解鎖更多功能',
    login: '登錄',
    register: '註冊',
    agree: '未註冊手機號碼登錄即可自動註冊，並代表您已同意用戶協議',
    uesrpwd: '用戶密碼登錄',
    wx: '微信登錄',
    qq: 'qq登錄',
    wb: '微博登錄',
    username: '用戶名 ',
    pwd: '密碼',
    creat: '創建賬戶',
    forget: '忘記密碼',
    send:'點擊發送驗證碼',
    repwd: '重置密碼',
    submit: '提交',
    reset: '重置',
    placeholder: {
      allsearch: '全局搜索',
      userphone: '請輸入手機號',
      userpwd: '請輸入密碼',
      enteryzm: '請輸入驗證碼',
      resetpwd: '請確認密碼',
      enterxq: '請輸入您的特殊需求',
      entering: '請輸入...',
      username: '請輸入用戶名',
      search: '搜索'
   },
   nobirth: '妳還未添加生辰八字',
   add: '添加',
   sm: '算命',
   bazi: '生辰八字',
   name: '姓名',
   gender: '性别',
   nan: '男',
   nv: '女',
   birthyear: '出生年月',
   birthtime: '出生時辰',
   birthaddress: '出生地',
   fellback: '意見反饋',
   liuyan: '如果您在網站和微商城發現任何問題，或者有更好的建議，歡迎給我們留言！',
   yishou: '已售',
   jian: '件',
   paystyle: '支付方式',
   wxpay: '微信支付',
   tuiwx: '推薦已在微信中綁定銀行卡的用戶使用',
   alipay: '支付寶支付',
   tuialipay: '安全快捷，可支持銀行卡支付',
   tuivisapay: '支持國際支付',
   useyouhui: '可用優惠券',
   orderinfo: '訂單信息',
   ordergoodslist: '商品清單',
   orderdily: '發貨信息',
   orderinfopay: '支付信息',
   ordertal: '總計',
   orderbz: '備註',
   newaddress: '新建收貨地址',
   addressshou: '新建收獲地址，保證商品順利送達',
   shipaddress:'收獲地址',
   noshipaddress: '有收貨地址寄不了快遞哦',
   addressadd: '添加',
   addresscomplate: '完成',
   nowdefault: '當前默認',
   updefault: '設為默認',
   addressjia: '+ 新建地址',
   editoradd: '編輯/添加地址',
   deleteguoqi: '刪除已過期優惠券',
   jiesuan: '結算',
   submitorder: '提交訂單',
   yibuy: '已購買',
   restsend: '重新發送'
  },
  en: {
    home: 'Home',
    telling: 'FortuneTelling',
    cart: 'Cart',
    personal: 'Personal',
    birth: 'Ba Zi',
    wds: 'Ask a master',
    jpclass: 'Excellent course',
    more: 'More',
    gobuy: 'Buy',
    carts: 'Shopping Cart',
    editor: 'editor',
    emptygoods: 'How about shopping cart empty? Go shopping.',
    goodshot: 'Shop for hot sale',
    youlike: 'You may like it.',
    chushou: 'Sell {{item.salesVolume}} pieces',
    defaults: 'default',
    completes: 'complete',
    Totalselection: 'Total selection',
    deletes: 'delete',
    mycoupon: 'My coupon',
    gouse: 'Use',
    goodsdetails: 'Commodity details',
    twdetails: 'Details',
    parameters: 'Parameters',
    attention: 'Attention',
    customerservice:'service',
    joinbuy: 'Add to cart',
    buy:'Purchase',
    cancel: 'Cancel',
    myorder: 'Order',
    orderdetails: 'Details',
    loginfo: 'Logistics information',
    system: 'System',
    orderpay: 'Your order has been produced, please pay at once.',
    payment: 'Amount of payment',
    note: 'Note information',
    ordernum: 'Order number',
    ordertime: 'Order time',
    paymethod: 'Payment method',
    gopay: 'If payment is to be made, payment is to be made.',
    cancellation: 'cancellation',
    immepayment: 'payment',
    looklog: 'Logistics',
    receipt: 'Receipt',
    binding: 'binding',
    allorders: 'Full order',
    waitpay: 'Pending ',
    waitgoods: 'Obligations',
    completed: 'Completed',
    serviced: 'Serviced',
    myaddress: 'Address',
    OnlineService: 'Online Service',
    setup: 'Set Up',
    messagecenter: 'Message center',
    AllMarkedRead: 'All marked as read.',
    AkeyEmpty: 'One key emptying',
    cancelqx: 'cancel',
    emptyAll: 'Do you want to empty all messages?',
    carefulEmpty: 'Can not be recovered after clearing, please handle with care.',
    determine: 'Determine',
    setpersonal: 'Modification of personal data',
    headportrait: 'Head Portrait',
    personaldata: 'Personal Data',
    bindingz: 'Binding',
    wbinding: 'Unbound',
    feedback: 'Feedback',
    shot: 'Shot',
    chooseimg: 'Select from the album',
    exitlogon: 'Exit Logon',
    phoneretrieval:'Mobile phone retrieval',
    retrpwd: 'Retrieve with registered cell phone number',
    next: 'Next',
    phone: 'Quick login of mobile phone',
    phonekc: 'Log on to K.Chan to unlock more functions.',
    login: 'Login',
    register: 'Register',
    agree: 'Unregistered mobile number login automatically registered, and on behalf of you have agreed to user agreement.',
    uesrpwd: 'User password login',
    wx: 'WeChat Login',
    qq: 'QQ Login',
    wb: 'Micro-blog',
    uselogin: 'Account login',
    username: 'User',
    pwd: 'Password',
    creat: 'Create an account',
    forget:'Forget the password',
    send: 'Send Code',
    repwd: 'Reset Password',
    submit: 'Submit',
    reset: 'Reset',
    placeholder: {
      allsearch: 'Global search',
      userphone: 'Please enter your phone number',
      userpwd: 'Please enter password',
      resetpwd: 'Please confirm the password',
      enteryzm: 'Please enter the verification code',
      enterxq: 'Please enter your special requirements',
      entering: 'Please enter the...',
      username: 'Please enter user name',
      search: 'search'
   },
   nobirth: "You haven't added Ba Zi",
   add: 'Add',
   sm: 'Fortune tellers',
   bazi: 'Ba Zi',
   name: 'Name',
   gender: 'Gender',
   nan: 'male',
   nv: 'female',
   birthyear: 'Date of birth',
   birthtime: 'Time of birth',
   birthaddress: 'Born address',
   fellback: 'Feedback',
   liuyan: 'If you find any problems on the website or wechat, or have better Suggestions, please leave us a message!',
   yishou: 'sold',
   jian: 'piece',
   paystyle: 'payment method ',
   wxpay: 'WeChat pay',
   tuiwx: 'recommended for users who are already tied to bank CARDS in WeChat',
   alipay: 'Alipay payment',
   tuialipay: 'safe and fast, bank card payment is supported',
   tuivisapay: 'support for international payments',
   useyouhui: 'Coupons available',
   orderinfo: 'order information',
   ordergoodslist: 'the goodslist',
   orderdily: 'shipping information',
   orderinfopay: 'payment information',
   ordertal: 'total',
   orderbz: 'remarks',
   newaddress: 'new delivery address ',
   addressshou: 'new harvest address to ensure smooth delivery of goods',
   shipaddress :' harvest address ',
   noshipaddress: 'there is no express delivery to the shipping address ',
   addressadd: 'add ',
   addresscomplate: 'finish ',
   nowdefault: 'current default ',
   addressjia: '+ new address ',
   editoradd: 'edit/add address',
   deleteguoqi: 'delete expired coupons ',
   jiesuan: 'settlement ',
   submitorder: 'submitorder ',
   yibuy: 'bought ',
   restsend: 'resend'
  } 
  
}