// 公共部分多语言
module.exports = {
  zh: {
    home: '首页',
    telling: '算命',
    cart: '购物车',
    personal: '个人',
    birth: '生辰八字',
    wds: '问大师',
    jpclass: '精品课程',
    more: '更多',
    gobuy: '去购买',
    carts: '购物车',
    editor: '编辑',
    emptygoods: '购物车空空如也，快去选购商品吧~',
    goodshot: '热卖商品',
    youlike: '你可能喜欢',
    defaults: '默认',
    completes: '完成',
    Totalselection: '全选',
    deletes: '删除',
    mycoupon: '我的优惠券',
    gouse: '去使用',
    goodsdetails: '商品详情',
    twdetails: '图文详情',
    parameters: '商品参数',
    attention: '购买须知',
    customerservice: '客服',
    joinbuy: '加入购物车',
    buy: '立即购买',
    cancel: '取消',
    myorder: '我的订单',
    orderdetails: '订单详情',
    loginfo: '物流信息',
    system: '系统',
    orderpay: '你的订单已生产，请立即支付',
    payment: '支付金额',
    note: '备注信息',
    ordernum: '订单编号',
    ordertime: '下单时间',
    paymethod: '支付方式',
    gopay: '如是待支付时，去支付',
    cancellation: '取消订单',
    immepayment: '立即支付',
    looklog: '查看物流',
    receipt: '确认收货',
    binding: '绑定',
    allorders: '全部订单',
    waitpay: '待付款',
    waitgoods: '待收货',
    completed: '已完成',
    serviced: '售后服务',
    myaddress: '我的地址',
    OnlineService: '在线客服',
    setup: '设置',
    messagecenter: '消息中心',
    AllMarkedRead: '全部标记为已读',
    AkeyEmpty: '一键清空',
    cancelqx: '取消',
    emptyAll: '是否清空所有消息',
    carefulEmpty: '清空后无法恢复，请谨慎处理',
    determine: '确定',
    setpersonal: '修改个人资料',
    headportrait: '头像',
    personaldata: '个人资料',
    bindingz: '绑定支付宝',
    wbinding: '未绑定',
    feedback: '意见反馈',
    shot: '拍摄',
    chooseimg: '从相册选择',
    exitlogon: '退出登录',
    phoneretrieval: '手机找回',
    retrpwd: '使用注册手机号码找回',
    next: '下一步',
    phone: '手机快捷登录',
    uselogin: '用户登录',
    phonekc: '登录k.chan，解锁更多功能',
    login: '登录',
    register: '注册',
    agree: '未注册手机号码登录即可自动注册，并代表您已同意用户协议',
    uesrpwd: '账号密码登录',
    wx: '微信登录',
    qq: 'qq登录',
    wb: '微博登录',
    username: '用户名',
    pwd: '密码',
    confirmpwd:'确认密码',
    creat: '创建账户',
    forget: '忘记密码',
    send: '发送验证码',
    repwd: '重置密码',
    submit: '提交',
    reset: '重置',
    placeholder: {
       allsearch: '全局搜索',
       userphone: '请输入手机号',
       userpwd: '请输入密码',
       enteryzm: '请输入验证码',
       resetpwd: '请确认密码',
       enterxq: '请输入您的特殊需求',
       entering: '请输入...',
       username: '请输入用户名',
       search: '搜索',
       inputSMS: '请输入短信验证码',
       choosearea:'请选择地区',
    },
    nobirth: '你还未添加生辰八字',
    add: '添加',
    sm: '算命',
    bazi: '生辰八字',
    name: '姓名',
   gender: '性别',
   nan: '男',
   nv: '女',
   birthyear: '出生年月',
   birthtime: '出生时辰',
   birthaddress: '出生地',
   fellback: '意见反馈',
   liuyan: '如果您在网站和微商城发现任何问题，或者有更好的建议，欢迎给我们留言！',
   yishou: '已售',
   jian: '件',
   gong: '共',
   paystyle: '支付方式',
   wxpay: '微信支付',
   weixinpay: '请使用微信浏览器访问',
   tuiwx: '推荐已在微信中绑定银行卡的用户使用',
   alipay: '支付宝 (国内钱包)',
   alipayxg:'支付宝 (香港钱包)',
   tuialipay: '安全快捷，可支持银行卡支付',
   tuivisapay: '支持国际支付',
   useyouhui: '可用优惠券',
   orderinfo: '订单信息',
   ordergoodslist: '商品清单',
   orderdily: '发货信息',
   orderinfopay: '支付信息',
   ordertal: '总计',
   orderbz: '备注',
   newaddress: '新建收货地址',
   addressshou: '新建收货地址，保证商品顺利送达',
   shipaddress: '收货地址',
   noshipaddress: '没有收货地址寄不了快递哦',
   addressadd: '添加',
   nowdefault: '当前默认',
   updefault: '设为默认',
   addressjia: '+ 新建地址',
   editoradd: '编辑/添加地址',
   deleteguoqi: '删除已过期优惠券',
   jiesuan: '结算',
   submitorder: '提交订单',
   yibuy: '已购买',
   restsend: '重新发送',
   backhome: '点击返回首页',
   deaddress: '若地址列表中没有送货地址，请在详细地址中，填写完整地址',
   lookresult: '查看结果',
   jiben: '基本',
   mingpan: '命盘',
   xipan: '细盘',
   dayun: '大运',
   liunian: '流年',
   pingyu: '评语',
   shuxiang: '属相',
   yangli: '阳历',
   yinli: '阴历',
   jieqi: '节气',
   xingzuo: '星座',
   xingxiu: '二十八星宿',
   kongwang: '空亡（年月）',
   minggong: '命宫',
   taiyuan: '胎元',
   taixi: '胎息',
   chenggu: '袁天罡称骨',
   weight: '重量',
   ordercenter: '订单中心',
   delecon: '删除确认',
   //11.19更改toast的语言切换   更改地址为 address/list   address/edit
   caredelete: '此操作不可逆,确认要删除该收货地址吗?',
   addressdelete: '地址删除成功',
   addressnode: '地址删除失败',
   failuredcaozuo: '操作失败',
   setdefaultaddress: '设置默认地址成功',
   setdefaultaddressno: '设置默认地址失败',
   addresschooseerror: '地址选择错误',
   correctphone: '请输入正确手机号',
   addresswaiting: '获取用户地址失败，请稍后再试',
   //   cart/edit
   choosedeletegoods: '请选择需要删除的商品',
   //   cart/settlement
   couponsdosenot: '此优惠券不满足使用条件',
   chooseaddress: '请选择收获地址',
   choosepayfize: '请先选择支付方式',
   //  coupon/list
   confirmdelete: '确认删除',
   deleteexpiredcoupons: '确认要删除过期优惠券吗？',
   Dontuse: '未使用',
   used: '已使用',
   expired: '已过期',
   //   fortunelist/fortunelist   fortunelist/index
   deleteconfirmation: '此操作不可逆,确认要删除该记录吗?',
   deletesuccess: '记录删除成功',
   deletefailure: '记录删除失败',
   //goods/detail
   warmprompt: '温馨提示',
   gologin: '您还未登录，立即前往登录',
   lookcart: '加入购物车成功，立即前往购物车查看',
   //  goods/list   index/index
   searchcontent: '请输入搜索内容',
   //  order/list
   cancelorder: '确认取消订单吗？',
   cancelsuccess: '订单取消成功',
   cancelerror: '订单取消失败',
   irreversible: '此操作不可逆,是否确认收货？',
   orderconfirm: '订单确认成功',
   orderfailure: '订单确认失败',
   alls: '全部',
   waitingpay: '待付款',
   waitinggoods: '待收货',
   completeds: '已完成',
   //fortunetellers/add
   fortime: '请选择',
   fortimes: '若时间不详，请选择默认时间',
   fortimeth: '请选择',
   // address/edit
   addname: '姓名',
   addinputname: '请输入姓名',
   addphone: '手机号码',
   addinputphone: '请输入手机号码',
   adderea: '所在区域',
   addinputerea: '请选择所在区域',
   adddetail: '详细地址',
   addinputdetail: '请填写详细地址',
   addgoodsdetail: '设为默认收获地址',
   addsave: '保存',
   addcorrectphone: '请输入正确格式手机号',
   //cart/list
   cartgobuy:'去支付',
   paytotal: '合计：',
   //goods/detail
   addCarts: '加入购物车',
   stepperTitle: '商品库存',
   shengyu: '剩余',
   lastchoose:'至少选择一件商品',
   xiangou:'限购',
   notkucun: '库存不够了',
   ren: '人',
   rens: '人',
   //cart/ settlement
   totallable: '合计: ',
   cancelButtonText:'取消',
   confirmButtonText: '确认',
   inputpwd: '请输入密码',
   againinputpwd:'请再次输入密码',
   twicepwd: '两次密码输入不一致!',
   duanxin: '您的短信验证码为',
   tishi:'温馨提示',
   man:'满',
   yuan: '元',
   SMS: '短信验证码',
   ContactUs: '联系我们',
   wechat: '微信(香港)：',
   wechat1: '微信(上海)：',
   choosecode:'请选择正确的国家代码!',
   codeandphone:'请填写正确的国家代码和手机号'

  },
  char: {
    home: '首頁',
    telling: '算命',
    cart: '購物車',
    personal: '個人',
    birth: '生辰八字',
    wds: '問大師',
    jpclass: '精品課程',
    more: '更多',
    gobuy: '去購買',
    carts: '購物車',
    editor: '編輯',
    emptygoods: '購物車空空如何，快去選購商品吧~',
    goodshot: '熱賣商品',
    youlike: '妳可能喜歡',
    defaults: '默認',
    completes: '完成',
    Totalselection: '全選',
    deletes: '刪除',
    mycoupon: '我的優惠券',
    gouse: '去使用',
    goodsdetails: '商品詳情',
    twdetails: '圖文詳情',
    parameters: '商品參數',
    attention: '購買須知',
    customerservice: '客服',
    joinbuy: '加入購物車',
    buy: '立即購買',
    cancel: '取消',
    myorder: '我的訂單',
    orderdetails: '訂單詳情',
    loginfo: '物流信息',
    system: '系統',
    orderpay: '妳的訂單已生產，請立即支付',
    payment: '支付金額',
    note: '備註信息',
    ordernum: '訂單編號',
    ordertime: '下單時間',
    paymethod: '支付方式',
    gopay: '如是待支付時，去支付',
    cancellation: '取消訂單',
    immepayment: '立即支付',
    looklog: '查看物流',
    receipt: '確認收貨',
    binding: '綁定',
    allorders: '全部訂單',
    waitpay: '待付款',
    waitgoods: '待收貨',
    completed: '已完成',
    serviced: '售後服務',
    myaddress: '我的地址',
    OnlineService: '在線客服',
    setup: '設置',
    messagecenter: '消息中心',
    AllMarkedRead: '全部標記為已讀',
    AkeyEmpty: '壹鍵清空',
    cancelqx: '取消',
    emptyAll: '是否清空所有消息',
    carefulEmpty: '清空後無法恢復，請謹慎處理',
    determine: '確定',
    setpersonal: '修改個人資料',
    headportrait: '頭像',
    personaldata: '個人資料',
    bindingz: '綁定支付寶',
    wbinding: '未綁定',
    feedback: '意見反饋',
    shot: '拍攝',
    chooseimg: '從相冊選擇',
    exitlogon: '退出登錄',
    phoneretrieval: '手機找回',
    retrpwd: '使用註冊手機號碼找回',
    next: '下壹步',
    phone: '手機快捷登錄',
    uselogin: '用戶登錄',
    phonekc: '登錄k.chan，解鎖更多功能',
    login: '登錄',
    register: '註冊',
    agree: '未註冊手機號碼登錄即可自動註冊，並代表您已同意用戶協議',
    uesrpwd: '用戶密碼登錄',
    wx: '微信登錄',
    qq: 'qq登錄',
    wb: '微博登錄',
    username: '用戶名 ',
    pwd: '密碼',
    confirmpwd:'確認密碼',
    creat: '創建賬戶',
    forget: '忘記密碼',
    send: '發送驗證碼',
    repwd: '重置密碼',
    submit: '提交',
    reset: '重置',
    placeholder: {
      allsearch: '全局搜索',
      userphone: '請輸入手機號',
      userpwd: '請輸入密碼',
      enteryzm: '請輸入驗證碼',
      resetpwd: '請確認密碼',
      enterxq: '請輸入您的特殊需求',
      entering: '請輸入...',
      username: '請輸入用戶名',
      search: '搜索',
      inputSMS: '請輸入短信驗證碼',
      choosearea:'請選擇地區'
   },
   nobirth: '妳還未添加生辰八字',
   add: '添加',
   sm: '算命',
   bazi: '生辰八字',
   name: '姓名',
   gender: '性别',
   nan: '男',
   nv: '女',
   birthyear: '出生年月',
   birthtime: '出生時辰',
   birthaddress: '出生地',
   fellback: '意見反饋',
   liuyan: '如果您在網站和微商城發現任何問題，或者有更好的建議，歡迎給我們留言！',
   yishou: '已售',
   jian: '件',
   gong: '共',
   paystyle: '支付方式',
   wxpay: '微信支付',
   weixinpay: '請使用微信瀏覽器訪問',
   tuiwx: '推薦已在微信中綁定銀行卡的用戶使用',
   alipay: '支付寶 (國內錢包)',
   alipayxg:'支付寶 (香港錢包)',
   tuialipay: '安全快捷，可支持銀行卡支付',
   tuivisapay: '支持國際支付',
   useyouhui: '可用優惠券',
   orderinfo: '訂單信息',
   ordergoodslist: '商品清單',
   orderdily: '發貨信息',
   orderinfopay: '支付信息',
   ordertal: '總計',
   orderbz: '備註',
   newaddress: '新建收貨地址',
   addressshou: '新建收貨地址，保證商品順利送達',
   shipaddress:'收貨地址',
   noshipaddress: '有收貨地址寄不了快遞哦',
   addressadd: '添加',
   addresscomplate: '完成',
   nowdefault: '當前默認',
   updefault: '設為默認',
   addressjia: '+ 新建地址',
   editoradd: '編輯/添加地址',
   deleteguoqi: '刪除已過期優惠券',
   jiesuan: '結算',
   submitorder: '提交訂單',
   yibuy: '已購買',
   restsend: '重新發送',
   backhome: '點擊返回首頁',
   deaddress: '若地址列表中沒有送貨地址，請在詳細地址中，填寫完整地址',
   lookresult: '查看結果',
   jiben: '基本',
   mingpan: '命盤',
   xipan: '細盤',
   dayun: '大運',
   liunian: '流年',
   pingyu: '評語',
   shuxiang: '屬相',
   yangli: '陽歷',
   yinli: '陰歷',
   jieqi: '節氣',
   xingzuo: '星座',
   xingxiu: '二十八星宿',
   kongwang: '空亡（年月）',
   minggong: '命宮',
   taiyuan: '胎元',
   taixi: '胎息',
   chenggu: '袁天罡稱骨',
   weight: '重量',
   ordercenter:'訂單中心',
   delecon: '刪除確認',
   caredelete: '此操作不可逆,確認要刪除該收貨地址嗎?',
   addressdelete: '地址刪除成功',
   addressnode: '地址刪除失敗',
   failuredcaozuo: '操作失敗',
   setdefaultaddress: '設置默認地址成功',
   setdefaultaddressno: '設置默認地址失敗',
   addresschooseerror: '地址選擇錯誤',
   correctphone: '請輸入正確手機號',
   addresswaiting: '獲取用戶地址失敗，請稍後再試',
   choosedeletegoods: '請選擇需要刪除的商品',
   couponsdosenot: '此優惠券不滿足使用條件',
   chooseaddress: '請選擇收獲地址',
   choosepayfize: '請先選擇支付方式',
   confirmdelete:'確認刪除',
   deleteexpiredcoupons: '確認要刪除過期優惠券嗎？',
   Dontuse: '未使用',
   used: '已使用',
   expired: '已過期',
   deleteconfirmation: '此操作不可逆,確認要刪除該記錄嗎?',
   deletesuccess:'記錄刪除成功',
   deletefailure: '記錄刪除失敗',
   warmprompt: '溫馨提示',
   gologin:'您還未登錄，立即前往登錄',
   lookcart: '加入購物車成功，立即前往購物車查看',
   searchcontent:'請輸入搜索內容',
   cancelorder:'確認取消訂單嗎？',
   cancelsuccess: '訂單取消成功',
   cancelerror: '訂單取消失敗',
   irreversible: '此操作不可逆,是否確認收貨？',
   orderconfirm: '訂單確認成功',
   orderfailure: '訂單確認失敗',
   fortime:'請選擇',
   fortimes:'若時間不詳，請選擇默認時間',
   fortimeth: '請選擇',
   alls: '全部',
   waitingpay: '待付款',
   waitinggoods: '待收貨',
   completeds: '已完成',
   addname: '姓名',
   addinputname: '請輸入姓名',
   addphone: '手機號碼',
   addinputphone: '請輸入手機號碼',
   adderea: '所在區域',
   addinputerea: '請選擇所在區域',
   adddetail: '詳細地址',
   addinputdetail: '請填寫詳細地址',
   addgoodsdetail: '設為默認收獲地址',
   addsave: '保存',
   addcorrectphone: '請輸入正確格式手機號',
   cartgobuy:'去支付',
   addCarts: '加入購物車',
   stepperTitle: '商品庫存',
   totallable: '合計: ',
   shengyu: '剩余',
   lastchoose:'至少選擇壹件商品',
   xiangou:'限購',
   notkucun: '庫存不夠了',
   paytotal: '合計',
   ren: '人',
   rens: '人',
   cancelButtonText:'取消',
   confirmButtonText: '確認',
   inputpwd: '請輸入密碼',
   againinputpwd:'請再次輸入密碼',
   twicepwd: '兩次密碼輸入不壹致!',
   duanxin: '您的短信驗證碼為',
   tishi:'溫馨提示',
   man:'滿',
   yuan: '元',
   SMS: '短信驗證碼',
   ContactUs: '聯系我們',
   wechat: '微信(香港)：',
   wechat1: '微信(上海)：',
   choosecode:'請選擇正確的國家代碼! ',
   codeandphone:'請填寫正確的國家代碼和手機號'
  },
  en: {
    home: 'Home',
    telling: 'FortuneTelling',
    cart: 'Cart',
    personal: 'Personal',
    birth: 'Ba Zi',
    wds: 'Ask a master',
    jpclass: 'Excellent course',
    more: 'More',
    gobuy: 'Buy',
    carts: 'Shopping Cart',
    editor: 'editor',
    emptygoods: 'How about shopping cart empty? Go shopping.',
    goodshot: 'Selling goods',
    youlike: 'You may like it.',
    chushou: 'Sell {{item.salesVolume}} pieces',
    defaults: 'default',
    completes: 'complete',
    Totalselection: 'Total selection',
    deletes: 'delete',
    mycoupon: 'My coupon',
    gouse: 'Use',
    goodsdetails: 'Commodity details',
    twdetails: 'Details',
    parameters: 'Parameters',
    attention: 'Attention',
    customerservice:'service',
    joinbuy: 'Add to cart',
    buy:'Purchase',
    cancel: 'Cancel',
    myorder: 'Order',
    orderdetails: 'Details',
    loginfo: 'Logistics information',
    system: 'System',
    orderpay: 'Your order has been produced, please pay at once.',
    payment: 'Amount of payment',
    note: 'Note information',
    ordernum: 'Order number',
    ordertime: 'Order time',
    paymethod: 'Payment method',
    gopay: 'If payment is to be made, payment is to be made.',
    cancellation: 'cancellation',
    immepayment: 'payment',
    looklog: 'Logistics',
    receipt: 'Receipt',
    binding: 'binding',
    allorders: 'Full order',
    waitpay: 'Pending ',
    waitgoods: 'Obligations',
    completed: 'Completed',
    serviced: 'Serviced',
    myaddress: 'Address',
    OnlineService: 'Online Service',
    setup: 'Set Up',
    messagecenter: 'Message center',
    AllMarkedRead: 'All marked as read.',
    AkeyEmpty: 'One key emptying',
    cancelqx: 'cancel',
    emptyAll: 'Do you want to empty all messages?',
    carefulEmpty: 'Can not be recovered after clearing, please handle with care.',
    determine: 'Determine',
    setpersonal: 'Modification of personal data',
    headportrait: 'Head Portrait',
    personaldata: 'Personal Data',
    bindingz: 'Binding',
    wbinding: 'Unbound',
    feedback: 'Feedback',
    shot: 'Shot',
    chooseimg: 'Select from the album',
    exitlogon: 'Exit Logon',
    phoneretrieval: 'Mobile phone retrieval',
    retrpwd: 'Retrieve with registered cell phone number',
    next: 'Next',
    phone: 'Quick login of mobile phone',
    phonekc: 'Log on to K.Chan to unlock more functions.',
    login: 'Login',
    register: 'Register',
    agree: 'Unregistered mobile number login automatically registered, and on behalf of you have agreed to user agreement.',
    uesrpwd: 'User password login',
    wx: 'WeChat Login',
    qq: 'QQ Login',
    wb: 'Micro-blog',
    uselogin: 'Account login',
    username: 'User',
    pwd: 'Password',
    confirmpwd:'Confirm password',
    creat: 'Create an account',
    forget: 'Forget the password',
    send: 'Send Code',
    repwd: 'Reset Password',
    submit: 'Submit',
    reset: 'Reset',
    placeholder: {
      allsearch: 'Global search',
      userphone: ' Phone number',
      userpwd: 'Password',
      resetpwd: 'Confirm password',
      enteryzm: 'Verification Code',
      enterxq: ' Special requirements',
      entering: 'Please enter the...',
      username: 'Please enter user name',
      search: 'search',
      inputSMS: 'Please enter SMS verification code',
      choosearea:'Select area'
   },
   nobirth: "You haven't added Ba Zi",
   add: 'Add',
   sm: 'Fortune tellers',
   bazi: 'Ba Zi',
   name: 'Name',
   gender: 'Gender',
   nan: 'male',
   nv: 'female',
   birthyear: 'Date of birth',
   birthtime: 'Time of birth',
   birthaddress: 'Born address',
   fellback: 'Feedback',
   liuyan: 'If you find any problems on the website or wechat, or have better Suggestions, please leave us a message!',
   yishou: 'sold',
   jian: 'pieces',
   gong: 'Total',
   paystyle: 'Payment method ',
   wxpay: 'WeChat pay',
   weixinpay: 'Please use the WeChat browser to access',
   tuiwx: 'recommended for users who are already tied to bank CARDS in WeChat',
   alipay: 'Alipay (domestic wallet)',
   alipayxg:'Alipay (Hong Kong wallet)',
   tuialipay: 'safe and fast, bank card payment is supported',
   tuivisapay: 'support for international payments',
   useyouhui: 'Coupons available',
   orderinfo: 'Order information',
   ordergoodslist: 'The goodslist',
   orderdily: 'Shipping information',
   orderinfopay: 'Payment infor',
   ordertal: 'Total',
   orderbz: 'Remarks',
   newaddress: 'new delivery address ',
   addressshou: 'new delivery address to ensure smooth delivery',
   shipaddress :'shipping address',
   noshipaddress: 'there is no express delivery to the shipping address',
   addressadd: 'add ',
   addresscomplate: 'finish ',
   nowdefault: 'current default ',
   updefault: 'Set to the default',
   addressjia: '+ new address ',
   editoradd: 'edit/add address',
   deleteguoqi: 'delete expired coupons ',
   jiesuan: 'settlement ',
   submitorder: 'Submitorder ',
   yibuy: ' Bought ',
   restsend: 'resend',
   backhome: 'Home',
   deaddress: 'If there is no shipping address in the address list, please in the detailed address, fill out the complete address',
   lookresult: 'Results',
   jiben: 'Basic',
   mingpan: 'Chart',
   xipan: 'Plate',
   dayun: ' Universiade',
   liunian: 'We',
   pingyu: 'Comments',
   shuxiang: 'Animal Sign',
   yangli: 'The Gregorian Calendar',
   yinli: 'The Lunar Calendar',
   jieqi: 'Solar Yerms',
   xingzuo: 'Sign',
   xingxiu: '28 Stars',
   kongwang: 'Empty Wu (Years)',
   minggong: 'It',
   taiyuan: 'Tire Yuan',
   taixi: 'Child Interest',
   chenggu: 'Highest day said yuan bone',
   weight: 'Weight',
   ordercenter: 'Order center',
   delecon: 'Confirm the deletion',
   //11.19更改toast的语言切换   更改地址为 address/list   address/edit
   caredelete: 'This operation is irreversible, and confirm to remove the shipping address?',
   addressdelete: 'Address deleted successfully',
   addressnode: 'Address delete failed',
   failuredcaozuo: 'The operation failure',
   setdefaultaddress: 'Set the default address successfully',
   setdefaultaddressno: 'Failed to set the default address',
   addresschooseerror: 'Address selection error',
   correctphone: 'Please enter a correct phone number',
   addresswaiting: 'Get the user address failed, please try again later',
   //   cart/edit
   choosedeletegoods: 'Please select need to delete the goods',
   //   cart/settlement
   couponsdosenot: 'This coupon does not meet the conditions of use',
   chooseaddress: 'Please select a harvest address',
   choosepayfize: 'Please select payment method',
   //  coupon/list
   confirmdelete:'Confirm the deletion',
   deleteexpiredcoupons: 'Confirm to delete expired coupons?',
   Dontuse: 'Dont use',
   used: 'Used',
   expired: 'Expired',
   //   fortunelist/fortunelist   fortunelist/index
   deleteconfirmation: 'This operation is irreversible, confirm want to delete this record?',
   deletesuccess:'Records deleted successfully',
   deletefailure: 'Record delete failed',
   //goods/detail
   warmprompt: 'Warm prompt',
   gologin:'You are not logged in, go to login immediately',
   lookcart: 'Add to cart success, immediately went to the shopping cart view',
   //  goods/list   index/index
   searchcontent:'Please input search content',
   //  order/list
   cancelorder:'Confirm cancel the order?',
   cancelsuccess: 'Order cancellation is successful',
   cancelerror: 'Order cancellation failure',
   irreversible: 'This operation is irreversible, whether to confirm the goods?',
   orderconfirm: 'Order confirmation success',
   orderfailure: 'Failure to identify the order',
   //fortunetellers/add
   fortime: 'Please select',
   fortimes: 'If the time is unknown, please select the default time',
   fortimeth: 'Please select',
   alls: 'All',
   waitingpay: 'Payment',
   waitinggoods: 'Goods',
   completeds: 'Completed',
   addname: 'Name',
   addinputname: 'Please enter your name',
   addphone: 'Phone number',
   addinputphone: 'Please enter the phone number',
   adderea: 'Area',
   addinputerea: 'Please select a region',
   adddetail: 'Detailed address',
   addinputdetail: 'Please fill out the detailed address',
   addgoodsdetail: 'Harvest is set to the default address',
   addsave: 'Save',
   addcorrectphone: 'Please input correct format of phone number',
   cartgobuy:'To pay for',
   addCarts: 'Add to cart',
   stepperTitle: 'Inventory',
   totallable: 'A combined: ',
   shengyu: 'The remaining',
   lastchoose:'Choose at least one item',
   xiangou:'For purchasing',
   notkucun: 'Out of stock',
   paytotal: 'A combined  ',
   ren:'people',
   rens: 'person',
   cancelButtonText:'cancel',
   confirmButtonText: 'confirm',
   inputpwd: 'Please enter your password',
   againinputpwd:'Please enter your password again',
   twicepwd: 'The two passwords do not match!',
   duanxin: 'Your SMS verification code is',
   tishi:'Warm prompt',
   man:'Full',
   yuan: 'yuan',
   SMS: 'Verification code',
   ContactUs: 'Contact Us',
   wechat: 'WeChat(HK)：',
   wechat1: 'WeChat(SHH)：',
   choosecode: 'Please select the correct country code',
   codeandphone:'Please fill in the correct country code and mobile phone number'
  } 
  
}